#!/usr/bin/env python3
"""Generate a hashed requirements.lock file from requirements.txt."""
from __future__ import annotations

import argparse
import hashlib
import shutil
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQUIREMENTS_TXT = ROOT / "requirements.txt"
DEFAULT_OUTPUT = ROOT / "requirements.lock"


def parse_requirements(path: Path) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "==" not in line:
            raise ValueError(f"Requirement '{line}' must pin an exact version")
        name, version = line.split("==", 1)
        pairs.append((name.strip(), version.strip()))
    return pairs


def download_package(name: str, version: str, directory: Path) -> list[Path]:
    subprocess.run(
        [
            "python",
            "-m",
            "pip",
            "download",
            "--no-deps",
            f"{name}=={version}",
            "-d",
            str(directory),
        ],
        check=True,
    )
    return list(directory.glob(f"{name}-{version}*"))


def hash_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(8192), b""):
            digest.update(chunk)
    return digest.hexdigest()


def generate_lock(requirements: list[tuple[str, str]], output: Path) -> None:
    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_path = Path(tmp_dir)
        lines: list[str] = [
            "# Locked dependency set for production deployments.",
            "# Generated by tools/generate_lock.py.",
        ]
        for name, version in requirements:
            pkg_dir = tmp_path / f"{name}-{version}"
            pkg_dir.mkdir(parents=True, exist_ok=True)
            artifacts = download_package(name, version, pkg_dir)
            if not artifacts:
                raise RuntimeError(f"No artifacts downloaded for {name}=={version}")
            lines.append(f"{name}=={version} \\")
            for artifact in artifacts:
                digest = hash_file(artifact)
                lines.append(f"    --hash=sha256:{digest}")
            shutil.rmtree(pkg_dir)
        output.write_text("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--requirements",
        default=REQUIREMENTS_TXT,
        type=Path,
        help="Source requirements.txt file",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        type=Path,
        help="Destination lock file path",
    )
    args = parser.parse_args()

    requirements = parse_requirements(args.requirements)
    generate_lock(requirements, args.output)
if __name__ == "__main__":
    main()
